# -*- coding: utf-8 -*-
# RANDOM_SEED = 123
#
#
# NN_LAYERS = [13,8,3]
#
# LEARN_PERCENTAGE = 0.8
#
# EPOCHS = 200
# LEARNING_RATE = 0.3
# ALPHA_MOMENTO = 0.1

ROWS_TO_SKIP = 6700
ROWS_COUNT = 301

# MLP
RANDOM_SEED = 21
#LEARN_PERCENTAGE = 0.95
WINDOW_SIZE = 2
#NEURONS_COUNT_HIDDEN = 8

#NEURONS_COUNT_KOHONEN = 8
#NN_LAYERS = [NEURONS_COUNT_KOHONEN, NEURONS_COUNT_HIDDEN, 3]
#EPOCHS = 100
LEARNING_RATE = 0.1
ALPHA_MOMENTO = 0.2

# KOHONEN
ALPHA_KOHONEN = 0.45
EPOCHS_KOHONEN = 100
NORMALIZE_PARAMETER = 4

# optimal
NEURONS_COUNT_KOHONEN = 2
NEURONS_COUNT_HIDDEN = 5
LEARN_PERCENTAGE = 0.95
EPOCHS = 100
NN_LAYERS = [NEURONS_COUNT_KOHONEN, NEURONS_COUNT_HIDDEN, 3]
